const SET_THING = 'SET_THING';
const SET_BAGS = 'SET_BAGS';
const SET_LOCALIZATION= 'SET_LOCALIZATION';
const ADD_WHO= 'ADD_WHO';
const REMOVE_WHO= 'REMOVE_WHO';
const SET_ORGANIZATION= 'SET_ORGANIZATION';
const SET_STREET= 'SET_STREET';
const SET_CITY= 'SET_CITY';
const SET_POST= 'SET_POST';
const SET_PHONE= 'SET_PHONE';
const SET_DATE = 'SET_DATE';
const SET_HOUR = 'SET_HOUR';
const SET_MESSAGE = 'SET_MESSAGE';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
    SET_THING,
    SET_BAGS,
    SET_LOCALIZATION,
    ADD_WHO,
    REMOVE_WHO,
    SET_ORGANIZATION,
    SET_STREET,
    SET_CITY,
    SET_POST,
    SET_PHONE,
    SET_DATE,
    SET_HOUR,
    SET_MESSAGE,
    CLEAR_ALL
}